tools:
  php_loc:
    enabled: true
    excluded_dirs:
    - vendor
    - tests
    - install
  php_pdepend: true
  php_sim: true
  sensiolabs_security_checker: true
  external_code_coverage: false
  php_code_coverage: true
  php_cs_fixer:
    config:
      level: psr2
  php_mess_detector:
    enabled: true
    filter:
      paths:
      - 'assets/lib/*'
      - 'assets/snippets/*'
build:
  environment:
    php:
      version: 5.6
      ini:
        'date.timezone': 'Europe/Moscow'
    rabbitmq: false
    mysql: 5.5             # 5.5 or 5.6 or 5.7
    postgresql: false
    mongodb: false
    elasticsearch: false
    redis: false
    memcached: false
    neo4j: false
    variables:
      DB_HOST: '127.0.0.1'
      DB_BASE: 'doclister'
      DB_USER: 'root'
      DB_PASSWORD: ''
      DB_PREFIX: 'modx_'
      DB_CHARSET: 'utf8mb4'
      DB_METHOD: 'SET NAMES'
      DB_COLLATION: 'utf8mb4_unicode_ci'
  dependencies:
    before:
    - mysql -h 127.0.0.1 -u root -e "SET GLOBAL sql_mode = ''"
    - mysql -h 127.0.0.1 -u root -e 'create database doclister'
    - mysql -h 127.0.0.1 -u root doclister < tests/database/site_templates.sql
    - mysql -h 127.0.0.1 -u root doclister < tests/database/site_tmplvars.sql
    - mysql -h 127.0.0.1 -u root doclister < tests/database/site_tmplvar_templates.sql
    - mysql -h 127.0.0.1 -u root doclister < tests/database/site_content.sql
    - mysql -h 127.0.0.1 -u root doclister < tests/database/site_tmplvar_contentvalues.sql
    - mysql -h 127.0.0.1 -u root doclister < tests/database/user_attributes.sql
    - mysql -h 127.0.0.1 -u root doclister < tests/database/manager_users.sql
  tests:
    override:
    - command: phpcs-run --standard=phpcs.xml
    - php-scrutinizer-run
    -
      command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
      coverage:
        file: 'clover.xml'
        format: 'php-clover'
checks:
  php: true
filter:
  excluded_paths:
  - tests/*
  - install/*
  - assets/images/*
  - assets/js/*
  - assets/snippets/DLUsers/tpl/*
  - assets/snippets/DocLister/config/*
